name: CI

on:
  push:
    branches: [develop, main, master]
  pull_request:
    branches: [develop, main, master]

jobs:
  quality:
    uses: lleontor705/ats-deploy-public/.github/workflows/quality-node.yml@main
    with:
      node-version: "22"
      package-manager: "bun"
      lint-command: "bun run check"
      enable-tests: false

  security:
    uses: lleontor705/ats-deploy-public/.github/workflows/security-scan.yml@main
